# 第1章  机器学习基础

机器学习的主要任务：
- 分类：将实例数据分到合适的分类中
- 回归：预测数值型数据


用于执行分类、回归、聚类和密度估计的机器学习算法：
- 监督学习(supervised learning)
    - k-近邻算法
    - 朴素贝叶斯算法
    - 支持向量机
    - 决策树
    - 线性回归
    - 局部加权线性回归
    - Ridge回归
    - Lasso最小回归系数估计
- 监督学习(unsupervised learning)
    - K-均值
    - 最大期望算法
    - DBSCAN
    - Parzen窗设计

## 1.1 NumPy函数库基础

In [ ]:
from numpy import *

In [ ]:
# 随机数组 Array
random.rand(4,4)

In [ ]:
# 转化为矩阵  Matrix
randMat = mat(random.rand(4,4))

invRandMat = randMat.I   # .I对矩阵进行求逆运算

invRandMat

In [ ]:
# 矩阵乘法
randMat * invRandMat  # 结果是单位矩阵

In [ ]:
# 创建单位矩阵
eye(4)

## 1.1 NumPy函数库基础

In [1]:
from numpy import *

In [7]:
# 随机数组 Array
random.rand(4,4)

array([[0.42175478, 0.06367183, 0.71310564, 0.10857678],
       [0.83093523, 0.92609681, 0.18511593, 0.61148358],
       [0.20399132, 0.17458753, 0.017827  , 0.86800779],
       [0.70053659, 0.82515303, 0.41810434, 0.78980089]])

In [8]:
# 转化为矩阵  Matrix
randMat = mat(random.rand(4,4))

invRandMat = randMat.I   # .I对矩阵进行求逆运算

invRandMat

matrix([[ 0.64241548, -0.86456074, -0.1517127 ,  0.59836752],
        [ 0.23952118,  9.46386424, -7.7955117 , -2.01372748],
        [ 0.83007901,  3.48130323, -1.85953518, -1.59670803],
        [-0.99774987, -7.98149695,  7.59559058,  2.48627826]])

In [9]:
# 矩阵乘法
randMat * invRandMat  # 结果是单位矩阵

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -5.55111512e-17],
        [-3.33066907e-16,  1.00000000e+00,  0.00000000e+00,
          2.22044605e-16],
        [-1.11022302e-16, -8.88178420e-16,  1.00000000e+00,
         -2.22044605e-16],
        [-2.22044605e-16, -8.88178420e-16, -1.77635684e-15,
          1.00000000e+00]])

In [10]:
# 创建单位矩阵
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])